### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by javi10823** [netbeast/react-native-appsee#1]
I have a problem whem I'm tryinig to build the project.

I followed the instructions: https://www.appsee.com/docs/ios/reactnative

<img width="406" alt="Captura de pantalla 2019-05-11 a la(s) 19 07 17" src="https://user-images.githubusercontent.com/1581454/57575412-1b75ef00-7420-11e9-81c1-88c08e1abbe0.png">

**node_modules/react-native-appsee/ios/RNAppsee.h:1:10: 'React/RCTBridgeModule.h' file not found**

Please help!

**Comment by Joncy** [comment]
Hi @javi10823, this repo is unmaintained since January 2019, please refer to the official Appsee documentation for more recent support. https://www.appsee.com/docs/ios/reactnative
